/*
** EPITECH PROJECT, 2019
** Logger
** File description:
** Logged exception objects
*/

#ifndef LOGGEDEXCEPTION_HPP_
    #define LOGGEDEXCEPTION_HPP_

	#include <exception>
	#include "LogLevel.hpp"
	#include "ALogTarget.hpp"
	#include "LogStdio.hpp"

namespace Log {

	///
	///@brief Exception wrapper logging its own 'what' upon construction
	///
	///@tparam ExceptionT Exception type to inherit from / to wrap
	///@tparam ClockT Clock type to be used for the log entries timestamps
	///@tparam StringT String type implementation
	///
	template<
		class ExceptionT = std::exception,
		class ClockT = std::chrono::system_clock,
		class StringT = std::string
	>
	class LoggedException : public ExceptionT {
		public:

			static_assert(std::is_convertible<ExceptionT *, std::exception *>(
				"Can't make a Logged Exception out of a non-exception object type"));

			///
			///@brief Compatible Log target base
			///
			///
			using LTarget = ALogTarget<ClockT, StringT>;

			///
			///@brief Log Entry type
			///
			///
			using LogEntryT = LogEntry<ClockT, StringT>;

			///
			///@brief Construct a new Logged Exception object
			///
			/// Logs 'what' into target upon construction
			///
			///@tparam Args Types of constrution arguments of inherited exception type
			///@param args Constrution arguments of inherited exception type
			///@param target Log target to log to
			///@param lv Log level of the exception's error message
			///
			template<typename... Args>
			LoggedException(Args&&... args, LTarget &target = LogErr, Level lv = Warning):
				ExceptionT(std::forward(args)...),
				_entry(what(), lv)
			{
				target.Log(_entry);
			}

			///
			///@brief Construct a new Logged Exception object
			///
			/// Logs 'what' into LogErr standard Log target upon construction
			///@sa LogErr
			///@tparam Args Types of constrution arguments of inherited exception type
			///@param args Constrution arguments of inherited exception type
			///@param lv Log level of the exception's error message
			///
			template<typename... Args>
			LoggedException(Args&&... args, Level lv = Warning):
				LoggedException(std::forward(args)..., , lv)
			{}

			///
			///@brief Destroy the Logged Exception object
			///
			///
			virtual ~LoggedException() = default;

			///
			///@brief Assignement operator
			///
			///@param right object to copy
			///@return LoggedException& self after assignement
			///
			LoggedException	&operator=(const LoggedException &right) = default;

			///
			///@brief Get the Entry object
			///
			///@return const LogEntryT& Log Entry generated by the exception
			///
			const LogEntryT				&getEntry() const
			{
				return _entry;
			}

			///
			///@brief Get the Level of the generated Log Entry object
			///
			///@return const Level Log Level of the generated log entry
			///
			const Level					getLevel() const
			{
				return _entry.getLevel();
			}

			///
			///@brief Get the Time Stamp of the generated Log Entry object
			///
			///@return const LogEntryT::TimeStampT& Time Stamp of the generated log entry
			///
			const LogEntryT::TimeStampT	&getTimeStamp() const
			{
				return _entry.getTimeStamp();
			}

		protected:
			LogEntry<ClockT, StringT>	_entry;
		private:
	};

}
#endif /* !LOGGEDEXCEPTION_HPP_ */
